package aifvalidate

import (
	"fmt"
	"sort"
	"strings"
)

// validateUnknownKeys is the generic unknown-key rejection and value-KIND check,
// derived from the reference's own types. Mirrors unknownKeys.ts in the JS port.
//
// The reference's save door decodes a flow with yaml.v3 KnownFields(true)
// (NewStrictFlowParser, parser.go). That refuses, at EVERY depth, a key the
// containing Go struct does not declare — a step-level `output:`, a typo such as
// `excutor:`, an unknown key inside `next:`, `error_strategy:`, a mock scenario
// step, a query parameter definition, an orchestrator trigger. It also fails to
// decode a value of the wrong KIND: `next: end` (a scalar where a mapping is
// required), a mapping where a string is required, a mapping where a list is.
// Both are "would not save", so both are errors.
//
// The key sets are not hand-listed: spec.KnownKeys is generated by reflection
// over the reference's Flow type with yaml.v3's field rules, and was checked
// against the reference's strict parser for every type and key (PARITY.md).
//
// What stays open, because the reference leaves it open: a Go map has
// author-chosen keys (steps, query definitions, mock_scenarios,
// executor_config), a Go interface (`any`) is never inspected (a step's query:,
// data:, a mock's content:), and a pre/post-processing entry has its own
// unmarshaller (divergence #12 keeps its shape out of scope).
//
// Scalars are judged for KIND only (not a mapping, not a list). Whether `5`
// fits an int field is left to the rules that already own those fields.
func validateUnknownKeys(flow doc, iss *issues) {
	reported := make(map[string]struct{}, len(iss.errors))
	for _, e := range iss.errors {
		if e.Code == codeUnknownYAMLKey || e.Code == codeInvalidType {
			reported[e.Code+"\x00"+e.Field] = struct{}{}
		}
	}
	w := knownKeyWalker{iss: iss, reported: reported}
	w.walk(flow, parseKnownKeyShape(spec.KnownKeys.Root), "")
}

// Shape spellings in spec.knownKeys.
const (
	shapeScalar     = "scalar"
	shapeAny        = "any"
	shapeMapPrefix  = "map<"
	shapeListPrefix = "list<"
	shapeSuffix     = ">"
)

type knownKeyShapeKind int

const (
	shapeKindScalar knownKeyShapeKind = iota
	shapeKindAny
	shapeKindStruct
	shapeKindMap
	shapeKindList
)

type knownKeyShape struct {
	kind knownKeyShapeKind
	name string         // shapeKindStruct: the type name
	elem *knownKeyShape // shapeKindMap / shapeKindList
}

// parseKnownKeyShape decodes one shape string. An unresolvable name is a spec
// defect, not a document defect, so it fails OPEN (any) rather than accusing
// every flow; TestKnownKeyShapesAllResolve keeps a shipped spec from having one.
func parseKnownKeyShape(text string) knownKeyShape {
	switch {
	case text == shapeScalar:
		return knownKeyShape{kind: shapeKindScalar}
	case text == shapeAny:
		return knownKeyShape{kind: shapeKindAny}
	case strings.HasPrefix(text, shapeMapPrefix) && strings.HasSuffix(text, shapeSuffix):
		elem := parseKnownKeyShape(text[len(shapeMapPrefix) : len(text)-len(shapeSuffix)])
		return knownKeyShape{kind: shapeKindMap, elem: &elem}
	case strings.HasPrefix(text, shapeListPrefix) && strings.HasSuffix(text, shapeSuffix):
		elem := parseKnownKeyShape(text[len(shapeListPrefix) : len(text)-len(shapeSuffix)])
		return knownKeyShape{kind: shapeKindList, elem: &elem}
	}
	if _, ok := spec.KnownKeys.Types[text]; ok {
		return knownKeyShape{kind: shapeKindStruct, name: text}
	}
	return knownKeyShape{kind: shapeKindAny}
}

// retiredGrammarKeyNames are the keys the reference DELETED from the grammar
// (retiredGrammarKeys, parser.go). Its refusal names them wherever they appear;
// the specific locations with full advice are reported by validateRetiredKeys,
// and this only keeps the generic message from calling a once-valid key a typo.
var retiredGrammarKeyNames = newSet([]string{
	"budget", "budget_exceeded_policy", "budget_max_per_child", "binary_results",
	"conversations", "max_retries", "message_templates", "unique_items",
})

type knownKeyWalker struct {
	iss      *issues
	reported map[string]struct{}
}

func (w knownKeyWalker) report(code, field, message, suggestion string) {
	id := code + "\x00" + field
	if _, done := w.reported[id]; done {
		return
	}
	w.reported[id] = struct{}{}
	w.iss.error(Issue{
		Field: field, Code: code, StepID: stepIDOfField(field),
		Message: message, Suggestion: suggestion,
	})
}

func (w knownKeyWalker) walk(value any, shape knownKeyShape, path string) {
	// A YAML null decodes to the zero value of any Go type.
	if value == nil {
		return
	}
	switch shape.kind {
	case shapeKindAny:
		return
	case shapeKindScalar:
		if isCollection(value) {
			w.report(codeInvalidType, path,
				fmt.Sprintf("'%s' must be a single value, not %s", path, kindName(value)), "")
		}
	case shapeKindList:
		items, ok := asSlice(value)
		if !ok {
			w.report(codeInvalidType, path,
				fmt.Sprintf("'%s' must be a list, not %s", path, kindName(value)), "")
			return
		}
		for i, item := range items {
			w.walk(item, *shape.elem, fmt.Sprintf("%s[%d]", path, i))
		}
	case shapeKindMap:
		m, ok := asRecord(value)
		if !ok {
			w.report(codeInvalidType, path,
				fmt.Sprintf("'%s' must be a mapping, not %s", path, kindName(value)), "")
			return
		}
		for _, key := range sortedKeys(m) {
			w.walk(m[key], *shape.elem, childPath(path, key))
		}
	case shapeKindStruct:
		m, ok := asRecord(value)
		if !ok {
			label := path
			if label == "" {
				label = "the flow"
			}
			w.report(codeInvalidType, path,
				fmt.Sprintf("'%s' must be a mapping, not %s", label, kindName(value)), "")
			return
		}
		keys := spec.KnownKeys.Types[shape.name]
		for _, key := range sortedKeys(m) {
			field := childPath(path, key)
			declared, known := keys[key]
			if known {
				w.walk(m[key], parseKnownKeyShape(declared), field)
				continue
			}
			where := " at the top level"
			if path != "" {
				where = fmt.Sprintf(" in '%s'", path)
			}
			retired := ""
			if retiredGrammarKeyNames.has(key) {
				retired = " It was removed from the grammar and AIgentFlow refuses to save a flow that still declares it."
			}
			w.report(codeUnknownYAMLKey, field,
				fmt.Sprintf("Unknown key '%s'%s. AIgentFlow refuses to save a flow with a key its grammar "+
					"does not declare, because the key would be silently dropped.%s", key, where, retired),
				"Known keys here: "+joinNames(sortedMapKeys(keys)))
		}
	}
}

func childPath(path, key string) string {
	if path == "" {
		return key
	}
	return path + "." + key
}

// stepIDOfField returns the step id a `steps.<id>…` finding belongs to.
func stepIDOfField(field string) string {
	rest, ok := strings.CutPrefix(field, keySteps+".")
	if !ok {
		return ""
	}
	if i := strings.IndexAny(rest, ".["); i >= 0 {
		return rest[:i]
	}
	return rest
}

func isCollection(v any) bool {
	switch v.(type) {
	case doc, []any:
		return true
	}
	return false
}

func kindName(v any) string {
	switch v.(type) {
	case []any:
		return "a list"
	case doc:
		return "a mapping"
	}
	return "a scalar"
}

func sortedMapKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
